# Generated by Django 4.2.2 on 2023-09-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='课程号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='课程名称')),
                ('credit', models.IntegerField(verbose_name='学分')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=8, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=4, verbose_name='性别')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('college', models.CharField(max_length=20, verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='课程号')),
                ('date', models.CharField(max_length=20, verbose_name='日期')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成绩')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('college', models.CharField(max_length=20, verbose_name='学院')),
                ('c_name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='app01.courseinfo', verbose_name='课程名称')),
                ('gid', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, related_name='gid', to='app01.studentinfo', to_field='sid', verbose_name='学号')),
                ('s_name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='app01.studentinfo', to_field='name', verbose_name='姓名')),
            ],
        ),
    ]
