# Generated by Django 4.2.2 on 2023-09-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeinfo',
            name='s_name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
